import {
  BadgeCheck,
  BriefcaseBusiness,
  Building2,
  CheckCircle2,
  ClipboardCheck,
  Clock3,
  FileCheck,
  FileCheck2,
  FileText,
  Globe2,
  Handshake,
  Headset,
  Home,
  Languages,
  Luggage,
  MapPin,
  MonitorCog,
  Plane,
  Route,
  SearchCheck,
  ShieldCheck,
  ShoppingBag,
  Utensils,
  UsersRound,
  Warehouse,
  type LucideIcon,
} from 'lucide-react'
import type { IconName } from '../types/site'

export const iconMap: Record<IconName, LucideIcon> = {
  badge: BadgeCheck,
  briefcase: BriefcaseBusiness,
  building: Building2,
  clipboardCheck: ClipboardCheck,
  check: CheckCircle2,
  clock: Clock3,
  documents: FileCheck2,
  fileCheck: FileCheck,
  file: FileText,
  globe: Globe2,
  handshake: Handshake,
  headset: Headset,
  home: Home,
  language: Languages,
  map: MapPin,
  monitor: MonitorCog,
  plane: Plane,
  route: Route,
  search: SearchCheck,
  shield: ShieldCheck,
  shopping: ShoppingBag,
  suitcase: Luggage,
  utensils: Utensils,
  users: UsersRound,
  warehouse: Warehouse,
}
